### ISSUE TITLE
Cannot initialize CUDA without ATen_cuda library

### ISSUE THREAD

**Issue by andmek** [facebookresearch/UnsupervisedMT#10] opened 2018-09-03 10:09 UTC
While I am trying to train an NMT model, I got the following error message. I build PyTorch 0.5 from source on Ubuntu 16.04 running Python3.5.

Traceback (most recent call last):
  File "main.py", line 242, in <module>
    encoder, decoder, discriminator, lm = build_mt_model(params, data)
  File "/home/gezmu/UnsupervisedMT/NMT/src/model/__init__.py", line 98, in build_mt_model
    return build_attention_model(params, data, cuda=cuda)
  File "/home/gezmu/UnsupervisedMT/NMT/src/model/attention.py", line 801, in build_attention_model
    encoder.cuda()
  File "/home/gezmu/umt/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/gezmu/umt/lib/python3.5/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/gezmu/umt/lib/python3.5/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/gezmu/umt/lib/python3.5/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/gezmu/umt/lib/python3.5/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library.

**Comment by andmek** [comment] 2018-09-03 12:14
I am using CPU PyTorch. Is there any solution?

**Comment by shawnzaru** [comment] 2018-09-03 12:42
I did some code changes (see Pull request), but it seems those are not enough (crashed at evaluation phase). You may need to do more changes if you want to be CPU-only.

**Comment by glample** [comment] 2018-10-12 13:42
I'll close this issue, as it seems related to the loading of the CUDA library and not the code of the NMT model itself. Feel free to re-open it if you think the problem is coming from this repo.

**Closed by glample** 2018-10-12 13:42 UTC
